apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cdc-couchbase-sync.fullname" . }}
  labels:
    {{- include "cdc-couchbase-sync.labels" . | nindent 4 }}
data:
  connection.yaml: |
    {{- toYaml .Values.connection | nindent 4 }}
  mapping.yaml: |
    {{- toYaml .Values.mapping | nindent 4 }}
