{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cdc-couchbase-sync.fullname" . }}
  labels:
    {{- include "cdc-couchbase-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  PG_CDC_PASSWORD: {{ .Values.secrets.pgPassword | quote }}
  CB_PASSWORD: {{ .Values.secrets.cbPassword | quote }}
  ORACLE_CDC_PASSWORD: {{ .Values.secrets.pgPassword | quote }}
  MSSQL_CDC_PASSWORD: {{ .Values.secrets.pgPassword | quote }}
{{- end }}
